- name: install nginx based on OS\
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install nginx if redhat
    ansible.builtin.dnf:
      name: nginx
      state: absent
    when: ansible_os_family == "RedHat"


  - name: install nginx if Debian
    ansible.builtin.apt:
      name: nginx
      state: absent
    when: ansible_os_family == "Debian" 