- name: loops
  hosts: backend
  tasks:
  - name: print user data
    ansible.builtin.debug:
      msg:  hello"{{ item }}" # item here is reserved keyword
    loop:
    - Thiru
    - Manish
    - Ramesh
    - Suresh  