- name: Default Function
  hosts: local
  connection: local
  vars:
    Person: Thiru
  tasks:
  - name: check the default function
    vars:
      Person: "Mahesh"
    ansible.builtin.debug:
      msg: "hello, {{ Person | default('Ramesh') }}" 